feat: add method to get a base URL, allow to pass remote base
nextcloud-libraries/nextcloud-router pull request #558
Opened 2024-01-23 11:34 UTC by Antreesy

.. place for a description ...

![image](https://github.com/nextcloud-libraries/nextcloud-router/assets/93392545/f3d48612-9361-4179-8093-122642d36e3b)

2024-01-23 12:51 UTC, ShGKme approved these changes

2024-01-23 12:53 UTC, ShGKme requested changes
New option is defined for 
- `generateUrl`
- `generateOcsUrl`

But implementation only covers:
- `generateOcsUrl`

2024-01-23 12:55 UTC, Antreesy commented
> * `generateUrl`

This method doesn't have a base part, so I assume, it's not applicable here?

https://github.com/nextcloud-libraries/nextcloud-router/blob/e3c586bb831d9a5c98006216488aa2c9356792a5/lib/index.ts#L101-L111

2024-01-23 13:15 UTC, ShGKme approved these changes

2024-01-23 13:24 UTC, nickvergessen commented
> This method doesn't have a base part, so I assume, it's not applicable here?

But you need to overwrite `getRootUrl()` ?

What about `generateRemoteUrl` and `linkToRemoteBase` for attachment handling?

2024-01-23 13:52 UTC, Antreesy commented
> But you need to overwrite `getRootUrl()` ?

`getBaseUrl` already includes `getRootUrl` as suffix (at the end of string). But in places, where only root is used, we need to consider it somehow, you're right

> What about `generateRemoteUrl` and `linkToRemoteBase` for attachment handling?

These methods are not affected by current changes.
We don't have yet a precedent, there it is needed, but if there is a necessity to connect to remote 'dav' service, then yes, I could modify it as well.

2024-01-23 21:38 UTC, skjnldsv commented
`remoteBase` seems confusing to me. 
It looks like we're talking about `remote.php` 😬

Do you have any other ideas for this variable name?

2024-01-23 21:40 UTC, nickvergessen commented
federation?

2024-01-23 21:42 UTC, skjnldsv commented
Or proxy something as a reverse proxy is a pretty standard concept.

2024-01-23 22:14 UTC, Antreesy commented
I'd call it as it actually should be called, `baseURL`, [like here](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base ), but this name is already used by Axios as one of the request options, and I'm afraid of interfering

2024-01-24 08:23 UTC, skjnldsv commented
`baseURL` seems to be the same as our use case?
Let's go for this?

2024-01-24 09:14 UTC, Antreesy commented
> Let's go for this?

Tested, won't be a problem, unless you pass a relative URL to axios request

2024-01-25 12:49 UTC, susnux commented on lib/index.ts
> + * @param {Number} options.baseURL URL to use as a base (defaults to current instance)
why is this a number?

2024-01-25 12:49 UTC, susnux commented on lib/index.ts
> +    const baseURL = options?.baseURL || getBaseUrl()
```suggestion
    const baseURL = options?.baseURL ?? getBaseUrl()
```

2024-01-25 12:50 UTC, susnux commented on lib/index.ts
> +    const baseURL = options?.baseURL || getBaseUrl()
```suggestion
    const baseURL = options?.baseURL ?? getBaseUrl()
```

2024-01-25 15:55 UTC, susnux commented
@Antreesy looks good to me, could you rebase and maybe add tests for the changed behavior?

2024-01-29 11:20 UTC, susnux approved these changes

2024-01-29 11:21 UTC, merged